# Generated by Django 5.1.5 on 2025-02-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(verbose_name=0.0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
