# Generated by Django 5.1.5 on 2025-02-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(),
        ),
    ]
